### ISSUE TITLE
Cant set rendered sizes of the picture element.

### ISSUE THREAD

**Issue by zhorzh** [rebelliard/angular-picture#1]
Hi! Thank you for making this directive open-source!

I have a question:
How can i set actual sizes of the rendered picture element?

My breakpoints are works ok, i have different image for every screen resolution, but image is always 100% of my viewport.

i am trying to do that like this:
https://gist.github.com/zhorzh/5331f49b13ce2c4cd142

**Comment by rebelliard** [comment]
This directive doesn't deal with this. [Picturefill](https://github.com/scottjehl/picturefill) is for showing the appropiate image given your desired media queries / viewport size, but the style and size itself is not dealt by it.
