### ISSUE TITLE
Specifying v0.1.1 in bower.json results in ENORESTARGET error

### ISSUE THREAD

**Issue by smt** [rebelliard/angular-picture#3]
```
bower angular-picture#0.1.1           ENORESTARGET No tag found that was able to satisfy 0.1.1
Additional error details:
No versions found in git://github.com/rebelliard/angular-picture.git
```

Since Bower relies solely on tags for package version info, would you mind tagging your 0.1.1 version in GitHub? The only way around this problem right now is to specify "*" as the version in bower.json, and that's generally not a great practice.

**Comment by smt** [comment]
[This article](http://bob.yexley.net/creating-and-maintaining-your-own-bower-package/) is a pretty good resource for Bower package maintenance :smiley_cat:

**Comment by rebelliard** [comment]
[Here](https://github.com/rebelliard/angular-picture/tree/v0.2.0) you go. Thanks for pointing that out.

**Comment by smt** [comment]
Thanks so much @rebelliard! :trophy:
