### ISSUE TITLE
Include license file

### ISSUE THREAD

**Issue by CallToPower** [rebelliard/angular-picture#5]
It would be nice if this project defines a license file to be able to use it in other projects.
Otherwise other projects can only view the source code but not use it, see [here](http://choosealicense.com/no-license) and [here](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license).

I do see "MIT" as license in the [package.json](https://github.com/rebelliard/angular-picture/blob/master/package.json), but don't think it's sufficient.

**Comment by rebelliard** [comment]
License added. Thanks.

**Comment by CallToPower** [comment]
Thanks!
